version: '3.1'

services:

  web:
    image: node:10-stretch
    restart: unless-stopped
    command: node out/index
    ports:
      - "${PORT}:${PORT}" # host:container
    links:
      - postgres
    working_dir: /urler/server
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      PASSWORD: ${PASSWORD}
    volumes:
      - ${URLER_PATH}:/urler/
  postgres:
    image: postgres:10-alpine
    restart: unless-stopped
    # ports:
    # - "5432:5432"
    environment:
      POSTGRES_USER: urler
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      - ${URLER_PATH}/data:/var/lib/postgresql/data
      - ${URLER_PATH}/scripts/postgres:/scripts/

