version: '3.1'

services:

  web:
    image: node:10-stretch
    command: node out/index
    ports:
      - "${PORT}:${PORT}" # host:container
    links:
      - db
    working_dir: /urler/server
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      PASSWORD: ${PASSWORD}
    volumes:
      - ${URLER_PATH}:/urler/
  db:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: urler
      POSTGRES_PASSWORD: ${PASSWORD}

